{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eagle-bank.fullname" . }}
  labels:
    {{- include "eagle-bank.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
  AUTH_JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
{{- end }}
